services:
  # MySQL (Auth DB)
  auth-mysql:
    image: mysql:8.0.33
    container_name: unduck-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${UNDUCK_AUTH_MYSQL_PASSWORD}
      MYSQL_DATABASE: unduck_auth_mysql
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - unduck-network
    restart: always

  # Redis
  redis:
    image: redis:7.4.1
    container_name: unduck-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - unduck-network
    restart: always

# Networks & Volumes
networks:
  unduck-network:
    driver: bridge

volumes:
  auth-db-data:
  redis-data: