version: "3.8"

services:
  # Config Server
  config:
    build:
      context: ./backend/unduck-config-service
      dockerfile: Dockerfile
    container_name: unduck-config
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_TOKEN: ${GIT_TOKEN}
    networks:
      - unduck-network
    restart: always


  # Gateway Service
  gateway:
    build:
      context: ./backend/unduck-gateway-service
      dockerfile: Dockerfile
    container_name: unduck-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:8888"
    depends_on:
      config:
        condition: service_healthy
      auth:
        condition: service_started
      platform:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - unduck-network
    restart: always

  # Auth Service
  auth:
    build:
      context: ./backend/unduck-auth-service
      dockerfile: Dockerfile
    container_name: unduck-auth
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:8888"
      AUTH_DB_PASSWORD: root1234
    depends_on:
      config:
        condition: service_healthy
      auth-mysql:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - unduck-network
    restart: always

  # Platform Service
  platform:
    build:
      context: ./backend/unduck-platform-service
      dockerfile: Dockerfile
    container_name: unduck-platform
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config:8888"
      PLATFORM_DB_PASSWORD: root1234
    depends_on:
      config:
        condition: service_healthy
      auth-mysql:
        condition: service_started
    networks:
      - unduck-network
    restart: always

  # MySQL (Auth DB)
  auth-mysql:
    image: mysql:8.4.0
    container_name: unduck-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: unduck_auth_mysql
    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - unduck-network
    restart: always

  # Redis
  redis:
    image: redis:7.4.1
    container_name: unduck-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - unduck-network
    restart: always

  # Frontend
  frontend:
    build:
      context: ./frontend/unduck-frontend-app
      dockerfile: Dockerfile
    container_name: unduck-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GATEWAY_URL=http://localhost:8080
    depends_on:
      gateway:
        condition: service_started
    networks:
      - unduck-network
    restart: always

# 네트워크 & 볼륨
networks:
  unduck-network:
    driver: bridge

volumes:
  auth-db-data:
  redis-data:
