server:
  port: 8888

spring:
  application:
    name: unduck-config-service

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/zmgu/unduck-config.git   # GitHub Config Repo
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          search-paths: config
          clone-on-start: true
          force-pull: true   # 항상 최신 버전으로 동기화

management:
  endpoints:
    web:
      base-path: /actuator         # health/info 엔드포인트 분리
      exposure:
        include: health,info       # 보안상 * 대신 필요한 항목만 노출
  endpoint:
    health:
      show-details: always         # "status": "UP" 세부정보 표시