server:
  port: 8081

spring:
  application:
    name: unduck-auth-service

  config:
    import: "optional:configserver:http://config:8888"

management:
  endpoint:
    health:
      show-details: always