spring:
  datasource:
    url: jdbc:mysql://unduck-auth-mysql:3306/unduck_auth_mysql?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: unduck-redis
    port: 6379

logging:
  level:
    root: INFO
